services:
  analyzers:
    image: analyzers:latest
    build:
      context: .
      dockerfile: Dockerfile
  quality:
    image: quality:latest
    build:
      context: .
      dockerfile: quality.Dockerfile
